parameters:
#    science_science_app.example.class: Science\ScienceAppBundle\Example

services:
#    science_science_app.example:
#        class: %science_science_app.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
